#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    right_lineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    center_lineFollower, sensorLineFollower)
#pragma config(Sensor, in5,    left_lineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  stop_button,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*
\*-----------------------------------------------------------------------------------------------4246-*/

void drive(int power = 127) {
	motor[rightMotor] = power;
	motor[leftMotor]  = power;
}

void turn_right(){
	const int ONE_FOURTH_ROTATION = 293;
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	while(abs(SensorValue[leftEncoder]) < ONE_FOURTH_ROTATION)
	{
		motor[rightMotor] = -127;
	  motor[leftMotor] = 127;
	}
}

void turn_left(){
	const int ONE_FOURTH_ROTATION = 293;
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	while(abs(SensorValue[leftEncoder]) < ONE_FOURTH_ROTATION)
	{
		motor[rightMotor] = 127;
	  motor[leftMotor] = -127;
	}
}

void drive_half_meter() {
	const int HALF_METER = 564;
	for(int i = 1; i<=5; i++) {
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
		while(abs(SensorValue[leftEncoder]) < HALF_METER) {
			drive();
		}
	}
}

task main()
{
	drive_half_meter();
	turn_left();
	drive_half_meter();
	turn_right();
	drive_half_meter();
	turn_right();
	drive_half_meter();

}
